# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0418e30829c32ee124dcbfc13fdbdd364db10e02696fd89eda26cb7bf697aee1edf5d9e76026ed041511c479eda991b86caf40ead691a5d18dfd3a78e6753156

test:
  secret_key_base: 6da659091d9848246eca0e9f0ce722ffd4fafe99686afef6635fa02963acd378e72827690c0ccf633dd4acdc70b02d845f32480e503e321de8f3d01d271febd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
